name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: |
          mvn clean package jar:jar appassembler:assemble -X -e
          mv ./target/appassembler ./ska-java
          zip -r ska-java.zip ska-java

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          prerelease: false
          draft: true
          files: |
            ska-java.zip
