name: Maven Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        server-id: ossrh 
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Publish Package
      run: mvn deploy
      env:
        JDK_JAVA_OPTIONS: --add-opens java.base/java.util=ALL-UNNAMED
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
